# Generated by Django 5.1.15 on 2026-10-06 19:43

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_alter_activity_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rate_bps', models.PositiveIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rate_bps', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('subtotal_minor', models.BigIntegerField(default=0)),
                ('tax_minor', models.BigIntegerField(default=0)),
                ('total_minor', models.BigIntegerField(default=0)),
                ('amount_paid_minor', models.BigIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.client')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit_price_minor', models.BigIntegerField()),
                ('tax_name', models.CharField(blank=True, max_length=50)),
                ('tax_rate_bps', models.PositiveIntegerField(default=0)),
                ('subtotal_minor', models.BigIntegerField(default=0)),
                ('tax_minor', models.BigIntegerField(default=0)),
                ('total_minor', models.BigIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.BigIntegerField()),
                ('paid_on', models.DateField(default=datetime.date.today)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('upi', 'UPI'), ('card', 'Card'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('recorded_by_id', models.BigIntegerField(blank=True, null=True)),
                ('recorded_by_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.invoice')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='invoicing_i_status_a811c1_idx'),
        ),
    ]
