# Generated by Django 5.1.15 on 2026-10-08 05:15

import apps.invoicing.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_activity_kind'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('reminder_offsets', models.JSONField(default=apps.invoicing.models.default_reminder_offsets)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('email_signature', models.CharField(blank=True, max_length=500)),
                ('last_daily_run_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='portal_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('anchor_date', models.DateField()),
                ('anchor_runs', models.PositiveIntegerField(default=0)),
                ('next_run_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_runs', models.PositiveIntegerField(blank=True, null=True)),
                ('runs_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=10)),
                ('auto_send', models.BooleanField(default=False)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('lines', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_by_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoices', to='crm.client')),
            ],
            options={
                'ordering': ['next_run_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoicing.recurringinvoice'),
        ),
        migrations.CreateModel(
            name='InvoiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_days', models.IntegerField()),
                ('skipped', models.BooleanField(default=False)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='invoicing.invoice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('invoice', 'offset_days'), name='uniq_reminder_per_offset')],
            },
        ),
        migrations.AddIndex(
            model_name='recurringinvoice',
            index=models.Index(fields=['status', 'next_run_date'], name='invoicing_r_status_271f89_idx'),
        ),
    ]
