# Generated by Django 5.1.15 on 2026-10-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_tag_client_address_line1_client_address_line2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('client_created', 'Client created'), ('client_archived', 'Client archived'), ('client_restored', 'Client restored'), ('contact_added', 'Contact added'), ('note_added', 'Note added'), ('lead_created', 'Lead created'), ('stage_changed', 'Stage changed'), ('lead_converted', 'Lead converted'), ('invoice_created', 'Invoice created'), ('invoice_sent', 'Invoice sent'), ('invoice_paid', 'Invoice paid'), ('invoice_voided', 'Invoice voided'), ('payment_recorded', 'Payment recorded'), ('payment_deleted', 'Payment removed')], max_length=30),
        ),
    ]
